### ISSUE TITLE
Doesn't remember page scroll position

### ISSUE THREAD

**Issue by esquien** [pylorak/reloadmatic#13]
Using Firefox Quantum 57.0

My dialy use requires me to scroll down the page various amounts.

If I use Firefox curly arrow [reload] the page position is remembered.

reloadmatic doesn't remember same. reloaded pg always starts at top.  am I missing an option ?

Cheers,  esquien

**Comment by pylorak** [comment]
Another nice idea! Let me check what options I have and I will get back to you here.

**Comment by pylorak** [comment]
Code committed, will be usable when next version is released.

**Comment by esquien** [comment]
Cool, TIA....

**Comment by pylorak** [comment]
1.5.1 is now released with the new feature inside.

**Comment by esquien** [comment]
This "ticket" shouldn't be closed as explained in detailed email directly to the author on 12/10.  1.5.1 still doesn't remember the scroll position and now screws up some numbers in the reloaded page.

**Comment by Hotkey-user** [comment]
Is there a shortcut key for set all tabs and reload all tabs now?
