### ISSUE TITLE
Sticky Reload

### ISSUE THREAD

**Issue by midnite420toker** [pylorak/reloadmatic#14]
I'm unable to find where to change setting to sticky reload. I've looked through the dropdown and it isn't there. I know it's said to change it in the addons but have no idea where that is. I can't find it. Could you please tell me how to change it to the sticky reload? I'd much appreciate it.

**Comment by pylorak** [comment]
It is in the right-click context menu (what you call dropdown, I think). If you don't see it there, then you have an old version and you need to update to addon. The latest version as of now it 1.5.0.

**Comment by midnite420toker** [comment]
Yes I was meaning the menu.

I had an older version just like you said. Installed 1.5.0 and stick reload is there. Thank you pylorak. This is something I use a lot so I'm really glad you made this for Firefox Quantum.
