### ISSUE TITLE
It doesn't work with local files

### ISSUE THREAD

**Issue by superruzafa** [pylorak/reloadmatic#16]
Hi.

I noticed that the extension doesn't reload the page when the URLs is a local file (file://)

Cheers.

**Comment by pylorak** [comment]
Just tested right now, and seems to work fine. Loaded a file into a tab (by drag and drop), address bar now says "file:///...", and after enabling refresh "Every 5 secs" in context menu, the tab refreshes its contents every 5 seconds. If I change the file contents with an external program, the changed contents are reflected in the tab.

**Comment by superruzafa** [comment]
Mmmm, now it works for me too.

If I observe that behavior again I'll try to figure out why this is happening.

Cheers.
