### ISSUE TITLE
Smart timing not working ?

### ISSUE THREAD

**Issue by cdubourg** [pylorak/reloadmatic#21]
Dear author,
I'm using ReloadMatic 1.5.2;
I thought that smarttiming feature would prevent the page reload while I'm typing text; 
Currently,  I'm typing in an online chat system, and the page reloads while I'm in the middle of a phrase, so I loose what I've already typed when page reloads.
Did I miss someting ?

thanks for your support,
I like your extension, it's very well done and handy.
Chris

**Comment by pylorak** [comment]
Smart timing waits only a few seconds before continuing the reload. So if you waited more than 2-3 seconds between two words or letters, the page would reload? This feature is meant for mouse navigation and clicks or maybe short text fields where you don't stop during typing.

I can still help, by extending the feature to give more time if typing into a text field. Would that help or is your problem of another nature?

**Comment by pylorak** [comment]
Hello, 1.6.0 is out and it contains new options for the Smart Timing feature. They are now configurable so you can fine-tune the settings to suit your liking. The default behavior has also been changed to prevent reloading completely if it detects the user typing. 

Feel free to let me know if you have any other feedback or input. I hope you like the changes, and if you are satisfied, I'd be grateful if you left a positive review on the addon's listing page over at Mozilla.
