### ISSUE TITLE
Style or icon on tab to indicate reload is active

### ISSUE THREAD

**Issue by rotan-hanrahan** [pylorak/reloadmatic#22]
There's no way to see if a particular page already has an active reload other than via the context menu. Is it possible to add an option that would allow an indication in the tab? Changing the text or background, adding an icon or some other indication would be a useful enhancement.

**Comment by pylorak** [comment]
Hi, I already tried to add this feature but unfortunately Firefox doesn't allow this (in tab headers) in its new addon system, only legacy addons could do this. However, I am working on adding a toolbar button to the browser where I can also show the menu in addition. There I can and will make indications.

**Comment by rotan-hanrahan** [comment]
With several windows each with several tabs, finding one that is auto-refreshing is non-trivial, and a badge on a toolbar icon won't address this problem. It would also be handy to visually confirm that the page into which one is currently typing is not on a reload timer. It's a pity about the Firefox tab styling limitation. Maybe you could inject a special character into the beginning of the page title? Unicode U+21BB ( &#8635; or &#x21bb; ) might be worth considering.

**Comment by pylorak** [comment]
That is really a good idea about changing the title, and a very nice find with U+21BB, thank you! If this is possible it will be included in the next released version for sure. I'll get back to you here in the comments to let you know.

**Comment by pylorak** [comment]
Hi! This worked out nicely and the feature has been incorporated into version 1.6.0, which I have just released. If you upgrade, you can start using it right away. There are also a bunch of other improvements in the new version.

Let me know if you have any other feedback or input. I hope you like the changes, and if you are satisfied, maybe you can leave a review about the addon. Thank you.

**Comment by rotan-hanrahan** [comment]
Nice job. I don't do reviews, but appreciate the improvement this change brings to the extension. Interesting observation about the effect of a page changing it's own title and the consequences for ReloadMatic. Your 100ms throttle should help. I suppose eventually the TITLE_BADGE feature will be an option the user can disable, but that can stay on the to-do list until the FF API allows one to attach context menus to tabs.

Keep up the good work.

**Comment by pylorak** [comment]
Yes, though I haven't yet seen any other addon adopting the same technique of setting a badge in the page's title. So my "observations" as of now are purely preventive and hypothetical, but better be safe than sorry. Making it an optional feature is okay and might even be justifiable even if there isn't any collision with other addons, so I might do it in a point release.

As for adding dynamic menus to tab headers, I am constantly monitoring Firefox's development in this aspect (there is movement!) and I guarantee I will be one of the firsts to make use of it.
