### ISSUE TITLE
right mouse click menu..

### ISSUE THREAD

**Issue by gooly** [pylorak/reloadmatic#24]
Hi,
I would suggest this behaviour of the menu that appears after a right mouse click.
Right now any selection is taken and the menu disappears.
This is annoying if you want (need) to select more than one item from that menu.
What if one click on the times in the upper part selects and closes the menu, but a selection on Remember page, .., Disable cache needs a double click to close the menu. One click on one of that's items just toggles them.

**Comment by pylorak** [comment]
This cannot be done with Firefox. The hiding and showing of the menu is completely under the browser's control without any possibility to influence it from addons. Sorry.
