### ISSUE TITLE
Looking for an add-on which will periodically load a specific URL, not just refresh the tab

### ISSUE THREAD

**Issue by Blackblot** [pylorak/reloadmatic#26]
Hello,

I have a webpage URL that is ultimately redirected to another URL.  For example, the page begins as www.mysite.com/start.htm and after some minutes the page is redirected to www.mysite.com/end.htm .

I then would like to reload www.mysite.com/start.htm, and not refresh the tab which now points to www.mysite.com/end.htm .

So am looking for an add-on which will periodically load a specific URL, not just refresh the tab.

Please advise if your add-on is capable of doing this.

Thanks.

**Comment by pylorak** [comment]
Yes, I will make this possible. I cannot give a specific ETA, but will probably be part of the next release.

**Comment by pylorak** [comment]
Support added in ReloadMatic 1.7.0. The feature is called "Fixed URL", and it allows you to define the URL ReloadMatic uses to load the page.
