### ISSUE TITLE
Do not trigger on Ctrl+T (for a new tab)

### ISSUE THREAD

**Issue by kreuvf** [pylorak/reloadmatic#28]
When on a tab with smart timing (and with disabling the timer on typing into a text field) using Ctrl+T for opening a new tab triggers the typing into a text field function disabling the timer. IMHO that should not trigger.

There may be other hotkeys that trigger the deactivation-on-typing feature although they probably shouldn't.

Do you need more infos for reproduction and can you reproduce the issue?

**Comment by pylorak** [comment]
Oh, good catch! I can reproduce it. I'll take a closer look during the next release.

**Comment by pylorak** [comment]
Fixed in version 1.7.0.
