### ISSUE TITLE
Automatic re-enable after POST, using previous URL

### ISSUE THREAD

**Issue by madduck** [pylorak/reloadmatic#29]
Let's say I enable reloadmatic on a given page, and I then interact with the page, causing a POST. It'll disable reloadmatic, and while I get a notification about that, I tend to then forget to reenable reloading when I done.

Could there be a setting per-page that would delay reloading (as per "smart timing"), but then actually reload the last-known-good (non-POST) URL of the site when the timer elapses?

**Comment by madduck** [comment]
Oh, I just realised this is very related to #26

**Comment by pylorak** [comment]
The "last known good" might sound like a good solution, but might actually be problematic. Aside from making sure the addon agrees with the user on what was the last-known-good page, there are other issues like how long the history should be tracked, differentiating wanted and unwanted redirect etc.

I'd propose to rather use the solution to #26 (yet to be implemented), though it will probably mean the user will have to set the URL manually (once).

**Comment by pylorak** [comment]
The "Fixed URL" feature in version 1.7.0 allows you to set the URL you wish to use during a reload. If you set this to the "last known good URL" (however the user defines it), then this should be what you want.
