### ISSUE TITLE
Issue: specific character in the tab title to identify that the timer is on is not appearing

### ISSUE THREAD

**Issue by syldub69** [pylorak/reloadmatic#30]
You told in issue #22 that you had implemented a specific character in the tab title to identify that the timer is on (Unicode U+21BB ( ↻ or ↻ )).
But I don't see any title change when I implement the timer. Is that normal?

**Comment by syldub69** [comment]
Now I see it... curious

**Comment by pylorak** [comment]
Possibly your addon wasn't yet updated to the newest version? Though theoretically FF checks once every day, and it has been some time since the correspondig release, so I'm not sure TBH.

**Comment by syldub69** [comment]
No, it was already the newest version tough... Anyway, now I see it well :o)
