### ISSUE TITLE
Behavior after user interaction on website: reload is deactivated

### ISSUE THREAD

**Issue by Eno77** [pylorak/reloadmatic#4]
I would like to have the actual behavior changed in a way that reload stays active, if one does something on the website.

At the moment if a reload activated tab is used, the reload will be deactivated, which forces to activate manually again, which is somewhat annoying.

Maybe with "POST" detection and warning like on ReloadEvery if reload shall stay active.

**Comment by pylorak** [comment]
Usually a user wants to keep reloading a specific page. Hence it makes sense then when the user navigates away from a page, reload for that tab gets disabled. So I will make an option to keep reloading turned on as you wish, but will make it disabled by default. You can than turn it on on tabs where you want to periodically reload every page.

**Comment by Wayne-B** [comment]
Yes, this is important.  When will the new option be available?

**Comment by pylorak** [comment]
Hi, I've just published the new version with this option (and other improvements) included :) Look for "Sticky reload", and please let me know what you think of the new version. Maybe leave a comment on the addon's page over at Mozilla.

As for other feature requests or bug reports, you are also welcome to open new tickets here.

**Comment by Eno77** [comment]
Thanks a lot for including this so quickly! Seems to work, I am happy for now ;)
You may close this "issue".
