### ISSUE TITLE
Reload at specific time

### ISSUE THREAD

**Issue by gooly** [pylorak/reloadmatic#7]
I have a whether forecast page that actualizes its value ~14 minutes after the full hour: [https://www.zamg.ac.at/cms/de/wetter/wetterwerte-analysen/wien](url)
It would be nice to have an option with a mask: "every HH:MM:SS", so that:
"every 12:15:00" reloads every day at 12:15:00
"every HH:14:00" reloads 14 minutes after every full hour and so on
I think I haven't seen that so far anywhere!
You can even think of using a mask with days:
"every DD:HH:MM:SS" to enable a reload at the beginning of a month ...

**Comment by pylorak** [comment]
Sorry, but this feature looks redundant to me. If a site updates for example at every hour 15 minutes, you can just set the reload period to 5, and you will get that update at most 5 minutes late, most likely much earlier. Updating a webpage once every 5 minutes won't tax your internet connection.

**Comment by gooly** [comment]
Well the advantage is that you don't have to wait for the specific time hour:15 to start an hourly reload, but you can define it whenever you want and it will work correctly if the pc or the browser had been down for some time (e.g. over night).

**Comment by pylorak** [comment]
Hi, Remember Page is now available in the newly released version 1.5 of the addon.
