### ISSUE TITLE
Button Option?

### ISSUE THREAD

**Issue by Lurkios** [pylorak/reloadmatic#9]
Is there any chance of us getting the option to have Reloadmatic as a button instead of (with option to remove it as a context menu item) a context menu entry? I know it doesn't work directly on the tab, but coming from reloadevery I miss my button.

Similar to what: https://addons.mozilla.org/en-US/firefox/addon/tab-reloader/ is doing.

Either way, your work is much appreciated. Was holding off on FF57 until this appeared.

**Comment by pylorak** [comment]
With the new WebExtensions API I would need to have all the code for the context menu duplicated for the button, and even more. Nevertheless I have also thought about adding a button, but I'm holding out a little more for a resolution of a [Firefox ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1253419), in the hope that it will turn out favorable for ReloadMatic.

**Comment by pylorak** [comment]
Now that tab header context menus are possible, the motivation for this ticket is gone. There would be no added value by a separate button.
